version: "3"

services:
  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.1.6
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042"
      - "19042:19042"
      - "10000:10000"
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/fixtures.cql:/fixtures.cql"
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:5.1.6
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9043:9042"
      - "19043:19042"
      - "10001:10000"
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:5.1.6
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9044:9042"
      - "19044:19042"
      - "10002:10000"
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

networks:
  web:
